# **Understanding numpy arrays**

In [3]:
!pip install numpy
import numpy as np
print(np.__version__)

1.26.4


In [4]:
# Creating a 1D NumPy array
array_1d = np.array([1, 2, 3, 4])
print("1D Array:", array_1d)  # Expected Output: 1D Array: [1 2 3 4]

# Creating a 2D NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)
# Expected Output:
# 2D Array:
# [[1 2 3]
#  [4 5 6]]

# Array attributes
print("Shape:", array_2d.shape)  # Expected Output: Shape: (2, 3) - 2 rows and 3 columns
print("Size:", array_2d.size)   # Expected Output: Size: 6 - Total 6 elements
print("Data Type:", array_2d.dtype)  # Expected Output: Data Type: int64 (or similar, depending on system)

1D Array: [1 2 3 4]
2D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Data Type: int64


In [6]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("Shape:", array_3d.shape)
print("Size:", array_3d.size)
print("Data Type:", array_3d.dtype)


Shape: (2, 2, 2)
Size: 8
Data Type: int64


# **Exercise: Exploring NumPy Arrays**


In [11]:
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)

print("Shape:", array_1d.shape)
print("Size:", array_1d.size)
print("Data Type:", array_1d.dtype)

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

print("Shape:", array_2d.shape)
print("Size:", array_2d.size)
print("Data Type:", array_2d.dtype)

1D Array: [1 2 3 4 5]
Shape: (5,)
Size: 5
Data Type: int64
2D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Data Type: int64


In [13]:
tenp_array = np.array([[['Sunday', 'Monday','Tuesday','Wednesday', 'Thursday', 'Friday', 'Saturday'], [8, 10, 9, 13, 14, 18, 16]]])
print("Weeks Temp Array:\n", tenp_array)

Weeks Temp Array:
 [[['Sunday' 'Monday' 'Tuesday' 'Wednesday' 'Thursday' 'Friday'
   'Saturday']
  ['8' '10' '9' '13' '14' '18' '16']]]


# **Array Indexing & Slicing**

In [14]:
array1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
fifth_element = array1[4]
print("5th element:", fifth_element)

5th element: 50


In [15]:
slice_array = array1[2:8]
print("Sliced array (3rd to 8th elements):", slice_array)


Sliced array (3rd to 8th elements): [30 40 50 60 70 80]


In [16]:
random_array = np.random.randint(10, 50, size=6)
greater_than_30 = random_array[random_array > 30]
print("Random array:", random_array)
print("Elements greater than 30:", greater_than_30)

Random array: [41 48 23 20 48 11]
Elements greater than 30: [41 48 48]


In [17]:
fancy_indices = [1, 3, 5]
fancy_selected = random_array[fancy_indices]
print("Selected elements using fancy indexing:", fancy_selected)


Selected elements using fancy indexing: [48 20 11]


# **Random Number Generation in Numpy**

In [20]:
rand = np.random.randint(10, 50, 6)
print(rand[rand>30])


[38 40 38 42]


In [21]:
x = np.array([1, 2, 3, 4, 5, 6, 7])
new = np.random.permutation(x)
new


array([7, 6, 5, 1, 4, 2, 3])

In [ ]:
two = np.array([[1,2], [3,4], [5,6]])
np.random.permutation(two)


In [19]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# **Exercises on Indexing and Slicing for Array Modification**

In [41]:
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

array1[4] = 50
print("5th element:", array1)

5th element: [ 1  2  3  4 50  6  7  8  9 10]


In [42]:
array1[3:8] = -array1[3:8]
print("Sliced array (3rd to 8th elements):", slice_array)

print("Modified array:", array1)


Sliced array (3rd to 8th elements): [ -4 -50  -6  -7  -8]
Modified array: [  1   2   3  -4 -50  -6  -7  -8   9  10]


In [43]:
random_array = np.random.randint(1, 100, 20)
random_array[random_array > 50] = -1
print("Modified random array:", random_array)

Modified random array: [-1  7 17 48 15 -1 -1 -1 -1 45 25 -1 49 13 -1 39 34  3 47 17]


In [56]:
array2D = np.random.randint(1, 10, (5, 5))

array2D

array([[7, 7, 1, 9, 4],
       [8, 4, 5, 1, 9],
       [5, 2, 4, 4, 9],
       [3, 8, 7, 7, 3],
       [3, 4, 8, 7, 2]])

In [57]:
for i in range(5):
  for j in range(5):
    # print (i,j)
    if i == j:
      array2D[i, j] = array2D[i ,j] *2
print(array2D)

[[14  7  1  9  4]
 [ 8  8  5  1  9]
 [ 5  2  8  4  9]
 [ 3  8  7 14  3]
 [ 3  4  8  7  4]]


In [58]:
for i in range(5):
  for j in range(5):
    if i + j == 4:
      array2D[i, j] = 0
print(array2D)

[[14  7  1  9  0]
 [ 8  8  5  0  9]
 [ 5  2  0  4  9]
 [ 3  0  7 14  3]
 [ 0  4  8  7  4]]


In [59]:
ar_z = np.zeros((5,5))
ar_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [60]:
ar_1 = np.ones((5,5))
ar_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# **Basic Operations with Arrays**

In [61]:
import numpy as np

# Creating sample arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition
print("Addition:", a + b)

# Broadcasting
print("Broadcasting with scalar:", a * 3)


Addition: [5 7 9]
Broadcasting with scalar: [3 6 9]


In [62]:
# Creating a 1D array
a = np.array([1, 2, 3])

# Adding a scalar value to the array
result = a + 5

print("Original Array:", a)
print("After Adding 5:", result)

Original Array: [1 2 3]
After Adding 5: [6 7 8]


In [67]:
# Creating a 1D array and a 2D array
a = np.array([0, 1, 2])
b = np.array([[0, 1, 2], [3, 4, 5]])

# Adding the 1D array to each row of the 2D array
result = a + b

print("1D Array:\n", a)
print("2D Array:\n", b)
print("Broadcasted Addition:\n", result)

1D Array:
 [0 1 2]
2D Array:
 [[0 1 2]
 [3 4 5]]
Broadcasted Addition:
 [[0 2 4]
 [3 5 7]]


In [69]:
# Creating two arrays
a = np.array([[1], [2], [3]])
b = np.array([1, 2, 3])

# Adding the two arrays
result = a + b

print("Array a:\n", a)
print("Array b:\n", b)
print("Broadcasted Addition:\n", result)

Array a:
 [[1]
 [2]
 [3]]
Array b:
 [1 2 3]
Broadcasted Addition:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [70]:
# Creating two incompatible arrays
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2])

try:
    result = a + b
except ValueError as e:
    print("Error:", e)

Error: operands could not be broadcast together with shapes (2,3) (2,) 


In [72]:
# Creating a 2D array and a 1D array
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])

# Element-wise multiplication
result = a * b

print("2D Array:\n", a)
print("1D Array:\n", b)
print("Broadcasted Multiplication:\n", result)


2D Array:
 [[1 2 3]
 [4 5 6]]
1D Array:
 [1 2 3]
Broadcasted Multiplication:
 [[ 1  4  9]
 [ 4 10 18]]


# **Reshaping & Transposing Arrays**

In [73]:
# Creating a 1D array
array = np.arange(1, 10)  # Array of numbers from 1 to 9

# Reshaping to a 3x3 matrix
reshaped_array = array.reshape(3, 3)
print("Reshaped to 3x3:\n", reshaped_array)

Reshaped to 3x3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [74]:
transposed_array = reshaped_array.T
print("Transposed array:\n", transposed_array)

Transposed array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [76]:
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr_1d)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [79]:
reshaped_array = arr_1d.reshape(4, 3)
print("Reshaped to 4x3:\n", reshaped_array)


Reshaped to 4x3:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [80]:
reshaped_array = arr_1d.reshape(2, 6)
print("Reshaped to 2x6:\n", reshaped_array)


Reshaped to 2x6:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [81]:
transposed_array = reshaped_array.T
print("Transposed array:\n", transposed_array)

Transposed array:
 [[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]


In [88]:
random_int_matrix = np.random.randint(1, 100, (3, 4))

print(random_int_matrix)



[[ 7 19 54 46]
 [92 14  5 24]
 [93 90 20 72]]


In [89]:
transposed_array = random_int_matrix.T
print("Transposed array:\n", random_int_matrix)

Transposed array:
 [[ 7 19 54 46]
 [92 14  5 24]
 [93 90 20 72]]


In [91]:
flattened_array = random_int_matrix.reshape(-1)

print(flattened_array)


[ 7 19 54 46 92 14  5 24 93 90 20 72]
