# **🌟 Exercise 1 : Array Creation and Manipulation**

In [25]:
!pip install numpy
import numpy as np

In [26]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# **🌟 Exercise 2 : Type Conversion and Array Operations**

In [27]:
arr2 = np.array([3.14, 2.17, 0, 1, 2])
arr2

array([3.14, 2.17, 0.  , 1.  , 2.  ])

In [28]:
arr2_int = np.array(arr2).astype(int)

print(arr2_int)


[3 2 0 1 2]


# **🌟 Exercise 3 : Working with Multi-Dimensional Arrays**

In [29]:
arr3 = np.arange(1, 10).reshape(3, 3)

print(arr3)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


# **🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers**

In [30]:
arr4 = np.random.rand(4, 5)

print(arr4)
print(arr4.shape)

[[0.00685276 0.45668682 0.75510346 0.37948433 0.37417714]
 [0.47509111 0.52848    0.77377093 0.02412026 0.11720306]
 [0.53730561 0.18243627 0.86489616 0.8180719  0.05131727]
 [0.1833169  0.47909893 0.46963929 0.67176258 0.90951893]]
(4, 5)


# **🌟 Exercise 5 : Indexing Arrays**

In [31]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])

second_row = arr5[1]

print(second_row)

[20 21 22 23 24]


# **🌟 Exercise 6 : Reversing elements**

In [35]:
arr6 = np.arange(10)
print(f'Before Rearange:', arr6)

# arr6[0] = 9
# arr6[9] = 0

reversed_array = array[-1]
print(f'After Rearange:', arr6)

Before Rearange: [0 1 2 3 4 5 6 7 8 9]
After Rearange: [0 1 2 3 4 5 6 7 8 9]


# **🌟 Exercise 7 : Identity Matrix**

In [37]:
arr7 = np.eye(4)

print(arr7)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# **🌟 Exercise 8 : Simple Aggregate Funcs**

In [44]:
arr8 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array_sum = np.sum(arr8)
array_avg = np.mean(arr8)

print(f"Sum: {array_sum}, Average: {array_avg}")


Sum: 45, Average: 4.5


# **🌟 Exercise 9 : Create Array and Change its Structure**

In [47]:
arr9 = np.arange(1, 21)
print(arr9)

reshaped_matrix = arr9.reshape(4, 5)

print(reshaped_matrix)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


# **🌟 Exercise 10 : Conditional Selection of Values**

In [56]:
arr10 = np.arange(10)
print(arr10)

odd_numbers = arr10[1::2]

print(odd_numbers)


[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
